package jetbrains.mps.LangDoc.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;

public class DocBitActions_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "jetbrains.mps.LangDoc.plugin.plugin.DocBitActions_ActionGroup";
  public DocBitActions_ActionGroup() {
    super("DocBitActions", ID);
    this.setIsInternal(false);
    this.setPopup(false);
    DocBitActions_ActionGroup.this.addAction("jetbrains.mps.LangDoc.plugin.plugin.ShowDocBits_Action");
    DocBitActions_ActionGroup.this.addAction("jetbrains.mps.LangDoc.plugin.plugin.HideDocBits_Action");
  }
}
