package jetbrains.mps.LangDoc.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.BaseKeymapChanges;

public final class DocBitKeys_KeymapChanges extends BaseKeymapChanges {
  public DocBitKeys_KeymapChanges() {
    add("jetbrains.mps.LangDoc.plugin.plugin.HideDocBits_Action", "ctrl alt shift C");
    add("jetbrains.mps.LangDoc.plugin.plugin.ShowDocBits_Action", "ctrl alt shift C");
  }
  @Override
  public String getScheme() {
    return "$default";
  }

}
