package jetbrains.mps.LangDoc.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.BaseKeymapChanges;

public final class MacOSX_KeymapChanges extends BaseKeymapChanges {
  public MacOSX_KeymapChanges() {
    replace("jetbrains.mps.LangDoc.plugin.plugin.HideDocBits_Action", "ctrl alt shift C");
    replace("jetbrains.mps.LangDoc.plugin.plugin.ShowDocBits_Action", "ctrl alt shift C");
  }
  @Override
  public String getScheme() {
    return "Mac OS X";
  }

}
