package jetbrains.mps.LangDoc.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.workbench.action.BaseAction;
import javax.swing.Icon;
import jetbrains.mps.workbench.action.ActionAccess;
import com.intellij.openapi.actionSystem.AnActionEvent;
import java.util.Map;
import jetbrains.mps.openapi.editor.update.Updater;
import jetbrains.mps.ide.editor.MPSEditorDataKeys;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.openapi.editor.EditorContext;

public class ShowDocBits_Action extends BaseAction {
  private static final Icon ICON = null;

  public ShowDocBits_Action() {
    super("Show Documentation Bits in the Main Editor", "Changes the projection to make documentation visible in the editor", ICON);
    this.setIsAlwaysVisible(false);
    this.setActionAccess(ActionAccess.UNDO_PROJECT);
  }
  @Override
  public boolean isDumbAware() {
    return true;
  }
  @Override
  public boolean isApplicable(AnActionEvent event, final Map<String, Object> _params) {
    Updater updater = event.getData(MPSEditorDataKeys.EDITOR_CONTEXT).getEditorComponent().getUpdater();
    String[] initialEditorHints = updater.getInitialEditorHints();
    if (initialEditorHints == null) {
      return true;
    }
    for (String hint : initialEditorHints) {
      if ("jetbrains.mps.LangDoc.editor.DocumentationHints.InlineDocBits".equals(hint)) {
        return false;
      }
    }
    return true;
  }
  @Override
  public void doUpdate(@NotNull AnActionEvent event, final Map<String, Object> _params) {
    this.setEnabledState(event.getPresentation(), this.isApplicable(event, _params));
  }
  @Override
  protected boolean collectActionData(AnActionEvent event, final Map<String, Object> _params) {
    if (!(super.collectActionData(event, _params))) {
      return false;
    }
    {
      EditorContext p = event.getData(MPSEditorDataKeys.EDITOR_CONTEXT);
      if (p == null) {
        return false;
      }
    }
    return true;
  }
  @Override
  public void doExecute(@NotNull final AnActionEvent event, final Map<String, Object> _params) {
    Updater updater = event.getData(MPSEditorDataKeys.EDITOR_CONTEXT).getEditorComponent().getUpdater();
    updater.setInitialEditorHints(new String[]{"jetbrains.mps.LangDoc.editor.DocumentationHints.InlineDocBits"});
    updater.update();
  }
}
